### ISSUE TITLE
AttributeError: This FileResponse instance has no `content` attribute. Use `streaming_content` instead.

### ISSUE THREAD

**Issue by kundansable** [yunojuno/django-request-profiler#17] opened 2018-12-19 05:25 UTC
I am getting above error while using this package, My Django version is 1.11.3, this package version 0.13.

**Comment by hugorodgerbrown** [comment] 2019-01-03 09:31
@kundansable do you have any more details - what was the full request / response. What content-type was it, what was the full stack trace?

**Comment by hugorodgerbrown** [comment] 2019-03-28 09:05
Closing this issue - not reproducible.

**Comment by frnhr** [comment] 2019-10-13 22:42
Getting the same error from any view that returns a `FileResponse`. Ref https://docs.djangoproject.com/en/2.2/ref/request-response/#fileresponse-objects

An `if` like this would probably solve the problem:
``` python
    def set_response(self, response):
        # ...
        if isinstance(response, StreamingHttpResponse):
            self.response_content_length = -1
        else:
            self.response_content_length = len(response.content)
```

**Comment by FlorinaAhmeti** [comment] 2021-11-08 15:18
Same here, I'm getting the same error from a view that returns a `FileResponse`

**Comment by hugorodgerbrown** [comment] 2021-11-08 15:19
Hi Florina - thanks for confirming this. Please feel free to submit a PR with a fix - all contributors are welcome.

**Comment by hugorodgerbrown** [comment] 2022-08-18 11:36
Closing due to lack of activity.

**Closed by hugorodgerbrown** 2022-08-18 11:36 UTC
